export default {
  id: 'invalidity',
  title: 'Proving invalidity',
  refs: { copiIL: '§10.6', copiSL: '§§4.3, 4.6', hurley: '§8.5' },
  card: 'Counterexamples in predicate logic: small worlds where the premises are true and the conclusion false.',
  summary: 'A proof shows that an argument is valid. To show that one is invalid, build a world, a domain of individuals with their properties, in which the premises are true and the conclusion false.',
  reading: [
    { h: 'Worlds' },
    'In sentential logic a counterexample is a row of a truth table. In predicate logic it is a small **model**: a set of individuals (the domain), a statement of which individuals each predicate holds of, and which individual each name picks out. A universal statement is true in a model when its instance is true of every individual; an existential one, when it is true of at least one.',
    { example: 'A counterexample', steps: [
      '“Some philosophers are Stoics. Some philosophers are Epicureans. So some philosophers are both.” {(∃x)Sx, (∃x)Ex / (∃x)(Sx • Ex)}',
      'Take two individuals, 1 and 2. Let S hold of 1 only, and E of 2 only.',
      'Then something is S (1) and something is E (2), so both premises are true. Nothing is both, so the conclusion is false.',
      'The argument is invalid. Notice that no world with a single individual would do: this counterexample needs two.',
    ], stepwise: true },
    { h: 'The finite universe method' },
    'Copi’s version of the same idea, which Hurley follows, replaces the quantifiers by what they amount to in a small domain. In a domain of two individuals, a and b, {(x)Fx} amounts to {Fa • Fb}, and {(∃x)Fx} to {Fa ∨ Fb}. The argument becomes a sentential one about {Fa}, {Fb} and so on, and the indirect truth table method from {@argument-tables} finds a counterexample if one exists in that domain. If none exists with one individual, try two, then three.',
    { h: 'What this method cannot do' },
    'For arguments using only one-place predicates, checking domains up to a known size settles validity: if no counterexample exists with up to 2ᵏ individuals (for k predicates), none exists at all. The exercises in this course are checked that way. But once relations enter, some invalid arguments have counterexamples only in infinite domains, and there is no general method that always decides validity. Church and Turing proved this in 1936.',
    'So in predicate logic, validity and invalidity are established by different kinds of evidence: a proof for one, a model for the other. When you cannot find either, you may simply not have looked hard enough.',
  ],
  exercises: [
    { id: 'in-exp-1', type: 'translate', prompt: 'In a domain of two individuals, a and b, write out what {(x)(Fx ⊃ Gx)} amounts to.', dictionary: { F: 'x is F', G: 'x is G' }, key: '(Fa ⊃ Ga) • (Fb ⊃ Gb)' },
    { id: 'in-exp-2', type: 'translate', prompt: 'In a domain of two individuals, a and b, write out what {(∃x)(Fx • ~Gx)} amounts to.', dictionary: { F: 'x is F', G: 'x is G' }, key: '(Fa • ~Ga) ∨ (Fb • ~Gb)' },
    { id: 'in-cm-1', type: 'countermodel', prompt: 'Build a counterexample.', argument: '(∃x)Sx, (∃x)Ex / (∃x)(Sx • Ex)', dictionary: { S: 'x is a Stoic', E: 'x is an Epicurean' } },
    { id: 'in-cm-2', type: 'countermodel', prompt: 'Build a counterexample: “All Stoics are philosophers, so all philosophers are Stoics.”', argument: '(x)(Sx ⊃ Px) / (x)(Px ⊃ Sx)', dictionary: { S: 'x is a Stoic', P: 'x is a philosopher' } },
    { id: 'in-cm-3', type: 'countermodel', prompt: 'Build a counterexample. (Everything is one or the other does not mean that one of them holds of everything.)', argument: '(x)(Fx ∨ Gx) / (x)Fx ∨ (x)Gx' },
    { id: 'in-cm-4', type: 'countermodel', prompt: 'Build a counterexample.', argument: '(∃x)Fx ⊃ (∃x)Gx / (x)(Fx ⊃ Gx)' },
    { id: 'in-cm-5', type: 'countermodel', prompt: 'Build a counterexample, with a name.', argument: 'Fa ⊃ (∃x)Gx, ~Ga / ~Fa' },
    { id: 'in-v-1', type: 'classify', mode: 'argument', prompt: 'Valid or invalid?', argument: '(x)(Fx ⊃ Gx), (∃x)~Gx / (∃x)~Fx' },
    { id: 'in-v-2', type: 'classify', mode: 'argument', prompt: 'Valid or invalid?', argument: '(x)(Fx ⊃ Gx), (∃x)~Fx / (∃x)~Gx' },
    { id: 'in-v-3', type: 'classify', mode: 'argument', prompt: 'Valid or invalid?', argument: '(x)Fx ∨ (x)Gx / (x)(Fx ∨ Gx)' },
    {
      id: 'in-two', type: 'choice', prompt: 'Why can no counterexample to {(∃x)Sx, (∃x)Ex / (∃x)(Sx • Ex)} have only one individual?',
      options: ['With one individual, if something is S and something is E, that one thing is both.', 'Because the argument is valid.', 'Because models must have two individuals.'],
      answer: 0,
    },
  ],
  margin: {
    title: 'Truth in a model',
    body: [
      'The idea of a model makes precise what “true in every situation” means for predicate logic. Tarski defined truth for formal languages in 1933 through *satisfaction*: an open formula like {Fx} is satisfied by some assignments of individuals to its variables, and a quantified statement is true when the right assignments satisfy its body. Every model in this lesson is a small Tarskian structure.',
      'Löwenheim showed in 1915 that a formula with a model has one whose domain is at most countably infinite, and that validity for one-place predicates is decidable. Behmann gave a decision procedure for that fragment in 1922. Then, in 1936, Church and Turing independently proved that no mechanical procedure decides validity for predicate logic as a whole: Hilbert’s *Entscheidungsproblem* has no solution.',
      'The consequence for practice is the one in the reading. Proof and counterexample are two separate searches, and the logician carries on both at once.',
    ],
    sources: ['copiIL', 'copiSL', 'tarski1933', 'lowenheim1915', 'behmann1922', 'church1936', 'turing1936', 'vanheijenoort1967', 'hurley2018'],
  },
};
