export default {
  id: 'arguments',
  title: 'Arguments, statements and form',
  refs: { copiIL: '§§1.2, 1.5–1.6', copiSL: '§§1.2–1.3', hurley: '§§1.1, 1.4–1.5' },
  card: 'What logic studies: when a conclusion follows from premises, and why that is a matter of form.',
  summary: 'Logic studies one relation: a conclusion *following from* premises. This lesson defines that relation and shows that whether it holds depends on the form of an argument, not on what the argument is about.',
  reading: [
    { h: 'Statements' },
    'A **statement** is a sentence that is either true or false. “Chrysippus wrote more than seven hundred books” is a statement: whether or not it is true, it is the kind of thing that can be. “Read Chrysippus” is not a statement (it is a command), nor is “Did Chrysippus write seven hundred books?” (a question). Logic deals only with statements, because only statements can stand as reasons for other statements.',
    'Statements are either **simple** or **compound**. A simple statement contains no other statement as a part: “It is day.” A compound statement is built out of others with words like *not*, *and*, *or*, *if … then* and *if and only if*: “If it is day, it is light.” Much of this course is about how the truth of a compound statement depends on the truth of its parts.',
    { h: 'Arguments' },
    { def: 'Argument', text: 'A group of statements, one of which (the **conclusion**) is claimed to follow from the others (the **premises**).' },
    'Words such as *therefore*, *so*, *hence* and *consequently* usually introduce a conclusion. Words such as *since*, *because*, *for* and *given that* usually introduce a premise. Neither list is foolproof: “since” can be about time, and many arguments carry no indicator words at all. The test is always what is being offered as a reason for what.',
    { example: 'Finding the conclusion', steps: [
      '“The will is free, since it can act otherwise than it does, and whatever can act otherwise is not determined.”',
      '*Since* flags what comes after it as a reason. So the premises are “the will can act otherwise than it does” and “whatever can act otherwise is not determined.”',
      'The conclusion is the statement the reasons support: “the will is free.” In standard form the conclusion comes last, after the premises.',
    ], stepwise: true },
    { h: 'Validity' },
    { def: 'Valid', text: 'An argument is **valid** when it is impossible for all its premises to be true and its conclusion false. Otherwise it is **invalid**.' },
    'Validity says nothing about whether the premises are in fact true. It is a claim about a connection: *if* the premises were true, the conclusion would have to be true as well. So a valid argument can have false premises and a false conclusion:',
    { quote: 'All philosophers are Stoics. Kant is a philosopher. Therefore, Kant is a Stoic.' },
    'The first premise is false and so is the conclusion, yet the argument is valid: there is no way for both premises to be true while the conclusion is false. Conversely, an invalid argument can have true premises and a true conclusion. What an invalid argument lacks is any guarantee.',
    { def: 'Sound', text: 'An argument is **sound** when it is valid and all its premises are true. A sound argument’s conclusion is therefore true.' },
    'Soundness is what we want from arguments in the end. Logic can settle validity; whether the premises are true is usually a question for the relevant science, or for philosophy itself.',
    { h: 'Form' },
    'Compare these two arguments.',
    { list: [
      'If it is day, it is light. It is day. Therefore, it is light.',
      'If the soul is a body, it can act and be acted upon. The soul is a body. Therefore, it can act and be acted upon.',
    ] },
    'They share nothing in subject matter, and yet they share a shape: *if the first, then the second; the first; therefore the second*. Replace each simple statement by a letter and the shape becomes visible. With A for the first statement and B for the second, both arguments have the form',
    { display: 'If A, then B.   A.   Therefore, B.', plain: true },
    'Every argument with this form is valid, because the form itself rules out true premises with a false conclusion. That is the central insight of formal logic: **validity is a matter of form**. It is why logic can be done with letters and symbols, and why one proof of a form settles every argument that has it.',
    { h: 'Showing invalidity by counterexample' },
    'Form also gives us a way to prove that an argument is invalid. Take an argument, find its form, and then look for a *substitution instance* of the same form whose premises are plainly true and whose conclusion is plainly false. If one exists, the form does not guarantee its conclusions, and so the original argument is invalid, even if its own premises and conclusion happen to be true.',
    { example: 'The counterexample method', steps: [
      '“If Seneca was a Stoic, he was a philosopher. Seneca was a philosopher. Therefore, Seneca was a Stoic.” Premises and conclusion are all true. Is the argument valid?',
      'Its form is: *If A, then B. B. Therefore, A.*',
      'Substitute: “If Paris is in Spain, Paris is in Europe. Paris is in Europe. Therefore, Paris is in Spain.” Both premises are true and the conclusion is false.',
      'So the form can lead from truth to falsehood, and the Seneca argument is invalid. Its conclusion is true, but its premises do not make it so. (This form has a name, *affirming the consequent*; you will meet it again in {@argument-forms}.)',
    ], stepwise: true },
  ],
  exercisesIntro: 'These first exercises are about concepts. From the next lesson on, the answers you type are checked by the logic engine.',
  exercises: [
    {
      id: 'arg-statements',
      type: 'choice',
      prompt: 'Which of these are statements?',
      options: [
        'The Stoics recognised five indemonstrable arguments.',
        'Consider the argument once more.',
        'Is every valid argument sound?',
        'If it is day, then it is light.',
      ],
      answer: [0, 3],
      why: [null, 'A command is neither true nor false.', 'A question is neither true nor false.', null],
      explain: 'The first and the last. A compound statement like the conditional is still a statement: it is true or false as a whole.',
    },
    {
      id: 'arg-conclusion',
      type: 'choice',
      prompt: '“No argument with true premises and a false conclusion is valid. This argument has true premises and a false conclusion. So this argument is not valid.” Which statement is the conclusion?',
      options: [
        'No argument with true premises and a false conclusion is valid.',
        'This argument has true premises and a false conclusion.',
        'This argument is not valid.',
      ],
      answer: 2,
      explain: '“So” marks the conclusion; the other two statements are offered as reasons for it.',
    },
    {
      id: 'arg-valid-false',
      type: 'choice',
      prompt: 'Can a valid argument have a false conclusion?',
      options: [
        'No: validity guarantees a true conclusion.',
        'Yes, but only if at least one premise is false.',
        'Yes, even when all its premises are true.',
      ],
      answer: 1,
      why: ['Validity guarantees a true conclusion only *if* the premises are true.', null, 'That is exactly what validity rules out.'],
      explain: 'A valid argument cannot lead from all-true premises to a false conclusion, so a false conclusion means some premise is false.',
    },
    {
      id: 'arg-invalid-true',
      type: 'choice',
      prompt: 'Can an invalid argument have true premises and a true conclusion?',
      options: ['Yes', 'No'],
      answer: 0,
      explain: 'Yes: the Seneca argument in the reading is an example. Invalidity means the premises do not guarantee the conclusion, not that the conclusion is false.',
    },
    {
      id: 'arg-sound',
      type: 'choice',
      prompt: '“All humans are mortal. Hypatia was human. Therefore, Hypatia was mortal.” This argument is:',
      options: ['valid and sound', 'valid but unsound', 'invalid'],
      answer: 0,
      explain: 'It is valid (its form guarantees the conclusion) and its premises are true, so it is sound.',
    },
    {
      id: 'arg-sound-2',
      type: 'choice',
      prompt: '“Every Stoic was Roman. Zeno of Citium was a Stoic. Therefore, Zeno was Roman.” This argument is:',
      options: ['valid and sound', 'valid but unsound', 'invalid'],
      answer: 1,
      why: ['Soundness also needs true premises. Zeno, the founder of Stoicism, came from Cyprus, and many Stoics were Greek.', null, 'If both premises were true, the conclusion would have to be. That is validity.'],
      explain: 'Valid, since the form guarantees the conclusion. Unsound, since the first premise is false: Zeno of Citium, the founder of the school, was from Cyprus.',
    },
    {
      id: 'arg-form',
      type: 'choice',
      prompt: '“If knowledge is perception, then knowledge can be false. Knowledge cannot be false. So knowledge is not perception.” Which argument has exactly the same form?',
      options: [
        'If it is day, it is light. It is not light. So it is not day.',
        'If it is day, it is light. It is light. So it is day.',
        'If it is day, it is light. It is not day. So it is not light.',
        'It is day or it is night. It is not night. So it is day.',
      ],
      answer: 0,
      why: [null, 'This affirms the consequent: “it is light” matches the second part, not a denial of it.', 'This denies the first part, while the original denies the second.', 'This uses “or”, not “if … then”.'],
      explain: 'Both have the form *If A then B; not B; so not A*. (This valid form is called *modus tollens*.)',
    },
    {
      id: 'arg-counterexample',
      type: 'choice',
      prompt: '“If Plato wrote the *Republic*, then Plato was an author. Plato did not write the *Republic*. So Plato was not an author.” Which substitution instance shows that this form is invalid?',
      options: [
        'If a whale is a fish, it lives in water. A whale is not a fish. So a whale does not live in water.',
        'If a whale is a mammal, it breathes air. A whale is a mammal. So a whale breathes air.',
        'If a whale is a fish, it has gills. A whale is not a fish. So a whale has no gills.',
      ],
      answer: 0,
      why: [null, 'This has a different form (affirming, not denying, the first part), and it is valid.', 'Premises true and conclusion true, so this instance proves nothing about the form.'],
      explain: 'Same form (*If A then B; not A; so not B*), true premises, false conclusion: whales do live in water. So the form is invalid, and the Plato argument (whose conclusion happens to be false anyway) is invalid too.',
    },
  ],
  margin: {
    title: 'What is it that is true or false?',
    body: [
      'Aristotle defined a deduction (*syllogismos*) as a discourse in which, certain things being laid down, something other than them follows of necessity from their being so. His logic studied relations among *terms*: “all A are B”, “some B are not C”.',
      'The Stoics, above all Chrysippus in the third century BCE, built a different logic whose units were whole propositions joined by “if”, “and” and “or”. That is the logic of the first half of this course. Its rediscovery as a logic of propositions, distinct from Aristotle’s, is largely owed to Łukasiewicz (1934) and to Mates’s *Stoic Logic* (1953).',
      'The Stoics also asked what the bearer of truth is. Sextus reports their answer: in speech three things are linked, the sound uttered, the external thing it is about, and what is *said*, the *lekton* or “sayable”. The first two are bodies; the sayable is incorporeal. A complete sayable that is true or false is an *axiōma*, a proposition. Stoic propositions could change their truth value: “it is day” is true now and false tonight.',
      'Modern logic inherits the question. Copi speaks of *propositions*, Hurley of *statements*, others of sentences. For the formal work in this course the choice rarely matters, but it returns when we reach sense and reference in {@part:predicate}.',
    ],
    sources: ['copiIL', 'copiSL', 'aristotlePrA', 'sextusM', 'dl7', 'mates1953', 'lukasiewicz1934', 'bobzienSEP', 'longsedley1987', 'kneale1962', 'hurley2018', 'forallx'],
  },
};
