export default {
  id: 'paradox',
  number: 18,
  title: 'Paradox',
  hurley: 'beyond Hurley',
  card: 'The Liar, Russell’s barber, Curry’s paradox and the heap: what logic can and cannot settle about them.',
  summary: 'A paradox is an apparently valid argument from apparently true premises to an apparently false conclusion. Logic can show exactly which claims cannot all be true together. It cannot tell you which one to give up; that is where philosophy starts.',
  reading: [
    { h: 'Three ways out' },
    'Faced with a paradox, there are only three options: reject a premise, reject the reasoning, or accept the conclusion. The first four parts of this lesson use classical logic to make each paradox exact. Rejecting the reasoning means changing the logic, and the next four lessons look at logics that do.',
    { h: 'The Liar' },
    '“This sentence is false.” Call it L. If L is true, then what it says holds, so it is false. If it is false, then what it says holds, so it is true. In symbols, L says of itself that it is not true: {L ≡ ~L}. Lesson 4 gives the verdict at once: {L ≡ ~L} is false on every row. In classical logic there can be no such sentence, yet English seems to contain one.',
    'The Liar is ancient. It is credited to Eubulides of Miletus in the fourth century BCE, and Chrysippus wrote several works on it. Modern responses divide by what they give up: Tarski denies that a language can contain its own truth predicate; Kripke lets the Liar fall into a gap, neither true nor false; Priest lets it be both. The next lesson builds the logics behind the last two.',
    { h: 'Russell’s paradox and the barber' },
    'In 1902 Russell wrote to Frege: consider the set of all sets that are not members of themselves. Is it a member of itself? If it is, it is not; if it is not, it is. Frege’s system assumed that every condition defines a set, and so it was inconsistent. Russell later gave a homely version. A village barber shaves all and only those villagers who do not shave themselves. Does he shave himself?',
    'In predicate logic, with {Sxy} for “x shaves y”, the barber’s description is {(x)(Sbx ≡ ~Sxx)}. Instantiate x to b and you get {Sbb ≡ ~Sbb}, a Liar-shaped contradiction. So the statement that there is such a barber is refutable, and its negation, {~(∃y)(x)(Syx ≡ ~Sxx)}, is a theorem you can prove with Hurley’s rules. The barber is no paradox: there is simply no such barber. Russell’s set is a paradox because the principle that every condition defines a set seemed as certain as logic itself.',
    { h: 'Curry’s paradox' },
    'Let C be a sentence that says: *if C is true, then A*, where A is anything at all, say “the moon is made of cheese.” Then {C ≡ (C ⊃ A)}, and from that biconditional A follows, by nothing more than Equiv, Exp, Taut and modus ponens. Curry’s paradox contains no negation. So the gap and glut theories, which tinker with negation, do not by themselves stop it; the pressure falls on the conditional, and in particular on the step (Exp and then Taut) that merges two uses of the assumption C into one, which logicians call *contraction*.',
    { h: 'The heap' },
    'A million grains of sand make a heap. Taking away one grain never turns a heap into a non-heap. So, after enough steps, one grain is a heap. Each premise is compelling, the reasoning is a long chain of modus ponens, and the conclusion is absurd. This is the *sorites* (from the Greek for heap), another paradox attributed to Eubulides. Its lesson concerns vague predicates, and each of the three ways out has able defenders.',
  ],
  exercises: [
    { id: 'px-liar', type: 'classify', mode: 'statement', prompt: 'The Liar says of itself that it is not true. Classify {L ≡ ~L}.', formulas: ['L ≡ ~L'] },
    { id: 'px-barber', type: 'proof', prompt: 'Prove that there is no barber who shaves all and only those who do not shave themselves.', dictionary: { S: 'x shaves y' },
      argument: '/ ~(∃y)(x)(Syx ≡ ~Sxx)',
      solution: [
        ['(∃y)(x)(Syx ≡ ~Sxx)', 'AIP'],
        ['(x)(Sax ≡ ~Sxx)', '1, EI'],
        ['Saa ≡ ~Saa', '2, UI'],
        ['(Saa ⊃ ~Saa) • (~Saa ⊃ Saa)', '3, Equiv'],
        ['Saa ⊃ ~Saa', '4, Simp'],
        ['(~Saa ⊃ Saa) • (Saa ⊃ ~Saa)', '4, Com'],
        ['~Saa ⊃ Saa', '6, Simp'],
        ['~Saa ∨ ~Saa', '5, Impl'],
        ['~Saa', '8, Taut'],
        ['Saa', '7, 9, MP'],
        ['Saa • ~Saa', '10, 9, Conj'],
        ['~(∃y)(x)(Syx ≡ ~Sxx)', '1–11, IP'],
      ] },
    { id: 'px-curry', type: 'proof', prompt: 'Curry’s paradox. From a sentence C that says “if C then A”, prove A. (Any A at all.)', argument: 'C ≡ (C ⊃ A) / A',
      solution: [
        ['[C ⊃ (C ⊃ A)] • [(C ⊃ A) ⊃ C]', '1, Equiv'],
        ['C ⊃ (C ⊃ A)', '2, Simp'],
        ['(C • C) ⊃ A', '3, Exp'],
        ['C ⊃ A', '4, Taut'],
        ['[(C ⊃ A) ⊃ C] • [C ⊃ (C ⊃ A)]', '2, Com'],
        ['(C ⊃ A) ⊃ C', '6, Simp'],
        ['C', '7, 5, MP'],
        ['A', '5, 8, MP'],
      ] },
    {
      id: 'px-curry-neg', type: 'choice',
      prompt: 'Why is Curry’s paradox a problem even for theories that let the Liar be neither true nor false, or both?',
      options: ['It uses no negation, so changing how negation behaves does not block it.', 'It is not valid in classical logic.', 'It depends on the law of excluded middle.'],
      answer: 0,
      why: [null, 'It is: you just proved it.', 'The proof above never uses excluded middle.'],
      explain: 'Gap and glut theories work on negation. Curry’s derivation runs through the conditional alone, so the trouble lies with rules like contraction and modus ponens.',
    },
    {
      id: 'px-frege', type: 'choice',
      prompt: 'Which principle of Frege’s system did Russell’s paradox refute?',
      options: ['That every condition defines a set of exactly the things that satisfy it.', 'That identity is reflexive.', 'That every set has a member.'],
      answer: 0,
      explain: 'Unrestricted comprehension. With the condition “is not a member of itself”, it yields exactly the barber-shaped contradiction you proved above.',
    },
    {
      id: 'px-heap', type: 'deny',
      prompt: 'The heap. These three claims cannot all be true. Which would you give up?',
      dictionary: { M: 'a million grains of sand make a heap', O: 'a single grain of sand makes a heap' },
      premises: ['M', 'M ⊃ O', '~O'],
      statements: [
        'A million grains of sand make a heap.',
        'Removing one grain never turns a heap into a non-heap; so if a million grains make a heap, a single grain does.',
        'A single grain is not a heap.',
      ],
      notes: [
        'You deny that there are heaps at all: vague terms apply to nothing. Unger defended this nihilism about ordinary things.',
        'You deny tolerance: somewhere a single grain makes the difference. Williamson’s epistemicism says there is a sharp cut-off that we cannot know; supervaluationists and degree theorists deny the premise in subtler ways.',
        'You accept that one grain is a heap. Almost no one takes this way out; it is useful to see why.',
      ],
    },
  ],
  margin: {
    title: 'Is logic the judge?',
    body: [
      'Quine sorted paradoxes into kinds: *veridical* ones, whose surprising conclusions turn out to be true; *falsidical* ones, which rest on a hidden fallacy; and *antinomies*, which bring an accepted way of reasoning into self-contradiction and force a revision of concepts. The barber is falsidical; Russell’s paradox was an antinomy that reshaped mathematics.',
      'Russell wrote to Frege in June 1902, as the second volume of Frege’s *Grundgesetze* was in the press; Frege replied that arithmetic tottered. Grelling and Nelson’s paradox of “heterological” (a word that does not apply to itself) has the same shape, and Curry published his in 1942.',
      'Carroll’s Tortoise from lesson 7 returns here. Curry’s paradox shows that a language cannot have both a sentence that says “if I am true then A” and an unrestricted modus ponens with contraction. Something about the link between rules and conditionals has to give, and which thing gives is exactly what logicians still dispute. Sainsbury’s *Paradoxes* is the best guide to the options; the encyclopedia entries go further.',
    ],
    sources: ['russell1902', 'grelling1908', 'curry1942', 'quine1966', 'sainsbury2009', 'unger1979', 'williamson1994', 'liarSEP', 'russellParadoxSEP', 'currySEP', 'soritesSEP', 'dl7'],
  },
};
