const SP = { s: 'Stoics', p: 'philosophers' };
const SYL = { s: 'Stoics', m: 'materialists', p: 'people who deny the void' };

export default {
  id: 'classes',
  title: 'Classes',
  refs: { copiIL: '§§5.2, 5.7–5.8', copiSL: '§7.1', langer: 'chs. V–VII' },
  card: 'Membership and inclusion, sums and products of classes, and categorical statements as class equations.',
  summary: 'A predicate sorts individuals into a class. Once classes are treated as things in their own right, they can be added, multiplied and complemented, and the old categorical statements become equations. This is the algebra Boole found, and the one Langer builds her book around.',
  reading: [
    { h: 'Members and classes' },
    'Logic cannot point at an individual, Langer observes; it can mention one “only as a member” of a class. Everything a predicate says about an individual it says by placing it in a class: “Reynard is a fox” puts Reynard in the class of foxes. Peano gave this relation its own sign, ε, so that “is a member of” would stop being confused with the other senses of “is”: identity, inclusion, predication. Langer writes {!Reynard ε fox}.',
    'A class is not a whole made of its members. Langer’s example is a college’s class of 1938, which makes a pledge in its first year. Twenty students leave and fifteen join; the class that redeems the pledge has different members, and is the same class. We know what the class of foxes is without knowing how many foxes there are.',
    { def: 'Membership and inclusion', text: 'a ε A: the individual a is a member of the class A. A < B: every member of A is a member of B. Langer defines inclusion by membership: “A < B” is equivalent by definition to “(x) : x ε A . ⊃ . x ε B”. In the notation of this course, with predicates for the classes, A < B says {(x)(Ax ⊃ Bx)}.' },
    'The two relations behave differently. Inclusion is transitive: if A < B and B < C, then A < C. Membership is not: Chrysippus is a member of the Stoics, and the Stoics are a member of the class of Hellenistic schools, but Chrysippus is not a Hellenistic school.',
    { h: 'Operations on classes' },
    'Given classes a and b, three new classes can always be formed, and two classes are always there.',
    { list: [
      '**The sum** a + b: whatever is in a or in b (or both).',
      '**The product** a × b, often written ab: whatever is in both. Langer glosses it as “the common part” of a and b.',
      '**The complement** −a: whatever is not in a.',
      '**The null class** 0: the class with no members. There is only one, since two classes with the same members are the same class.',
      '**The universe class** 1: the class of everything in the universe of discourse.',
    ] },
    'Langer insists on a distinction that is easy to lose here. The **universe of discourse**, which she writes K, is the collection of things a system talks about; the **universe class** 1 is a class, and so an element of the system when the system is about classes. De Morgan, who introduced the phrase “universe of discourse”, warned against running the two together; Venn, she argues, did exactly that.',
    { h: 'Categorical statements as equations' },
    'Here is the step that turns the syllogism into algebra. “All Stoics are philosophers” says that nothing is a Stoic without being a philosopher: the class of Stoics that are not philosophers is empty.',
    'In predicate logic, {(x)(Sx ⊃ Px)} says the same as {~(∃x)(Sx • ~Px)}. In the algebra of classes it is an equation.',
    { list: [
      '**A** All S is P: s × −p = 0.',
      '**E** No S is P: s × p = 0.',
      '**I** Some S is P: s × p ≠ 0.',
      '**O** Some S is not P: s × −p ≠ 0.',
    ] },
    'Copi writes the complement with a bar, S P̄ = 0 for the A statement; Langer writes S < P, or S × −P = 0. The content is the same, and it is the **Boolean interpretation** of {@square}: A and E deny that a class has members, I and O assert that it has some. So A does not imply I. If there are no Stoics, s × −p = 0 is true and s × p ≠ 0 is false.',
    { example: 'Barbara as algebra', steps: [
      '“All materialists deny the void; all Stoics are materialists; so all Stoics deny the void.” With m, p, s for the three classes:',
      'The premises are m × −p = 0 and s × −m = 0. The conclusion is s × −p = 0.',
      'Anything in s × −p is in s, so it is in m (since s × −m is empty); being in m, it is in p (since m × −p is empty). So s × −p has no members.',
      'The course decides such questions by turning each equation back into a statement about individuals and searching for a countermodel, which for statements like these always finds one if there is one.',
    ], stepwise: true },
    { h: 'Diagrams' },
    'Euler drew classes as circles, one inside another for inclusion and apart for exclusion; Venn drew overlapping circles for every combination of classes and shaded the empty ones. Langer explains why a drawing can do logic at all. Areas in a plane, related by lying inside one another, satisfy the same laws as classes related by inclusion, so “any two systems of the same logical form … may always be each other’s diagrams”. The circles are not pictures of the classes. They share their form, and the lesson after next makes “sharing a form” precise.',
    { h: 'Dots, as Langer writes them' },
    'Langer introduces the dot notation at this point in her book (ch. VII §5), and asks her readers to use it “as freely as possible”. The course can show every formula this way: choose **Principia** at the top of the page. A single dot between two statements means “and”; dots beside ⊃, ∨ or ≡ act as brackets, and more dots bind more widely. Her example of transitivity reads {!(a, b, c) : a nt b . b nt c . ⊃ . a nt c}: for any a, b and c, if a is north of b and b is north of c, then a is north of c. In this course’s letters that is {%(x)(y)(z) : Nxy . Nyz . ⊃ . Nxz}.',
  ],
  exercises: [
    { id: 'cl-1', type: 'classeq', prompt: 'Write as a class equation: “All Stoics are philosophers.”', dictionary: SP, key: 's × −p = 0', wrong: ['s × p ≠ 0', 's × p = 0', 'p × −s = 0'] },
    { id: 'cl-2', type: 'classeq', prompt: 'Write as a class equation: “No Epicurean is a Stoic.”', dictionary: { e: 'Epicureans', s: 'Stoics' }, key: 'e × s = 0', wrong: ['e × −s = 0'] },
    { id: 'cl-3', type: 'classeq', prompt: 'Write as a class equation (or inequation): “Some philosophers are not Stoics.”', dictionary: SP, key: 'p × −s ≠ 0', wrong: ['p × −s = 0', 's × −p ≠ 0'] },
    { id: 'cl-4', type: 'classeq', prompt: 'Write as a class equation: “Only the wise are free.”', dictionary: { w: 'the wise', f: 'the free' }, key: 'f × −w = 0', wrong: ['w × −f = 0'] },
    { id: 'cl-5', type: 'classeq', prompt: 'The Stoics held that everything that exists is a body. Write it as a class equation.', dictionary: { e: 'things that exist', b: 'bodies' }, key: 'e × −b = 0', alternatives: ['−e + b = 1'] },
    { id: 'cl-6', type: 'classeq', prompt: 'Write as a class equation: “Everything is either a body or incorporeal.”', dictionary: { b: 'bodies', i: 'incorporeals' }, key: 'b + i = 1', alternatives: ['−b × −i = 0'], wrong: ['b × i = 0'] },
    { id: 'cl-v1', type: 'classvalid', prompt: 'Barbara, in class equations. Does the conclusion follow?', dictionary: SYL, premises: ['m × −p = 0', 's × −m = 0'], conclusion: 's × −p = 0' },
    { id: 'cl-v2', type: 'classvalid', prompt: 'Does the conclusion follow?', dictionary: SYL, premises: ['p × −m = 0', 's × −m = 0'], conclusion: 's × −p = 0' },
    { id: 'cl-v3', type: 'classvalid', prompt: 'Subalternation, in the Boolean interpretation: from “All S is P”, does “Some S is P” follow?', dictionary: SP, premises: ['s × −p = 0'], conclusion: 's × p ≠ 0' },
    { id: 'cl-v4', type: 'classvalid', prompt: 'And with the existential import made explicit, as a premise that there are Stoics?', dictionary: SP, premises: ['s × −p = 0', 's ≠ 0'], conclusion: 's × p ≠ 0' },
    {
      id: 'cl-eps', type: 'choice', prompt: 'In which of these does “is” mean membership (ε) rather than inclusion (<)?',
      options: ['Zeno is a Stoic.', 'The Stoics are philosophers.', 'Every sage is free.', 'Chrysippus is a head of the Stoa.'],
      answer: [0, 3],
      why: [null, 'This relates two classes: every Stoic is a philosopher.', 'Two classes again: the sages are included in the free.', null],
      explain: 'Membership relates an individual to a class; inclusion relates a class to a class.',
    },
    {
      id: 'cl-trans', type: 'choice', prompt: 'Why is membership not transitive, when inclusion is?',
      options: [
        'Because a class can itself be a member of a class, without its members being members of that class.',
        'Because membership is symmetric.',
        'Because the null class has no members.',
      ],
      answer: 0,
      explain: 'Chrysippus ε Stoics and Stoics ε schools, but not Chrysippus ε schools. Russell’s paradox ({@paradox}) comes from letting classes be members freely.',
    },
    { id: 'cl-dots-1', type: 'translate', structural: true, prompt: 'Rewrite with brackets: {%P . Q . ⊃ . R}', dictionary: {}, key: '(P • Q) ⊃ R', wrong: ['P • (Q ⊃ R)', '~P ∨ (Q ⊃ R)'] },
    { id: 'cl-dots-2', type: 'translate', structural: true, prompt: 'Rewrite with brackets: {%P ⊃ Q . Q ⊃ P}', dictionary: {}, key: '(P ⊃ Q) • (Q ⊃ P)', wrong: ['P ≡ Q', 'P ⊃ [(Q • Q) ⊃ P]'] },
  ],
  margin: {
    title: 'Is a class a whole?',
    body: [
      'Boole’s *Laws of Thought* (1854) treated classes with the signs of arithmetic, and found that one law separated logic from number: {!xx = x}, the class of things that are x and x is just x. Jevons, Peirce and Schröder reworked his system into the “Boole–Schröder algebra” that Langer teaches. Burris and Legris tell the story in the Stanford Encyclopedia.',
      'Langer’s insistence that a class is not a whole made of its members has a rival. Leśniewski built an alternative to set theory, mereology, on the other reading: a “class” of things is the whole they compose, and the part–whole relation is transitive where membership is not. Russell, in *The Principles of Mathematics*, had already distinguished the class “as many” from the class “as one”, and struggled with how they are related. Varzi’s and Simons’s encyclopedia entries set out the two traditions.',
      'The diagrams have their own history. Euler used circles in letters written in the early 1760s to a German princess and published in 1768; Venn’s 1880 paper introduced the overlapping circles that bear his name. Langer’s point about them, that a diagram works because it shares the form of what it diagrams, is her general theory of symbols in miniature: she developed it in *Philosophy in a New Key* (1942), distinguishing the “discursive” symbolism of language and logic from the “presentational” symbolism of images and music.',
    ],
    sources: ['langer1937', 'copiIL', 'copiSL', 'boole1854', 'algebraLogicSEP', 'mereologySEP', 'lesniewskiSEP', 'russell1903', 'euler1768', 'venn1880', 'langer1942', 'langerSEP', 'demorgan1847'],
  },
};
